# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LunarDb < Formula
  desc "Database snapshot tool for PostgreSQL databases. Installs the `lunar` command."
  homepage "https://github.com/leonvogt/lunar"
  version "0.0.1-beta06"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta06/lunar_Darwin_x86_64.tar.gz"
      sha256 "70446ccf73904da80853a7fcff1194688445d54009047453276bbaabcc257987"

      def install
        bin.install "lunar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta06/lunar_Darwin_arm64.tar.gz"
      sha256 "6c9c5cb0a0efb11b70a4ea1215eaf3ddc436fe34a508f974490482c866843527"

      def install
        bin.install "lunar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta06/lunar_Linux_x86_64.tar.gz"
      sha256 "29258cfcf92f2896a44e48be7f7371779eba71713eacf5bc02b55eb3b7af07d5"
      def install
        bin.install "lunar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta06/lunar_Linux_arm64.tar.gz"
      sha256 "f46600b07cd6a78be5abb78b80b565f1b413801f9b82adeff7975f423b1dba1f"
      def install
        bin.install "lunar"
      end
    end
  end
end
