# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lunar < Formula
  desc "Database snapshot tool for PostgreSQL databases"
  homepage "https://github.com/leonvogt/lunar"
  version "0.0.1-beta03"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta03/lunar_Darwin_x86_64.tar.gz"
      sha256 "29cafd06b9ac69dabdd3a3a12105f10710e37cfea622d704b0405b822da09dbb"

      def install
        bin.install "lunar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta03/lunar_Darwin_arm64.tar.gz"
      sha256 "fe0b98ccc2ecc1a5fcf5060b744b5fd0963e31b244bbf78307ed3d509bd453e0"

      def install
        bin.install "lunar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta03/lunar_Linux_x86_64.tar.gz"
      sha256 "2d1e9c65da7fd145eff9f3395af27302580ffeadcc8dae4e8f779e5d9847fbad"

      def install
        bin.install "lunar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta03/lunar_Linux_arm64.tar.gz"
      sha256 "1928458191d773604a024393340a3661f30ccc9148c98ed335d68b828eb51f00"

      def install
        bin.install "lunar"
      end
    end
  end
end
