# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lunar < Formula
  desc "A database snapshot tool for PostgreSQL databases."
  homepage "https://github.com/leonvogt/lunar"
  version "0.0.1-beta02"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta02/lunar_Darwin_x86_64.tar.gz"
      sha256 "96141583da2116569a7994d573f37800ffb2a69e67c7e3c97e4797df0816e8fc"

      def install
        bin.install "lunar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta02/lunar_Darwin_arm64.tar.gz"
      sha256 "981c3fde33e9738aa040da0f0bd8a332c43184d47aa2b9b899ac35333a8658e1"

      def install
        bin.install "lunar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta02/lunar_Linux_x86_64.tar.gz"
      sha256 "7f3c1f30eda04769ac9b481985cff44e08b30dc2f4cadc142be07872d8854de7"

      def install
        bin.install "lunar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta02/lunar_Linux_arm64.tar.gz"
      sha256 "103fd987b0d4fed9dab30567ed68e03226bbd5776ecd31d4bf0d717e313c4c54"

      def install
        bin.install "lunar"
      end
    end
  end
end
