# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LunarDb < Formula
  desc "Database snapshot tool for PostgreSQL databases"
  homepage "https://github.com/leonvogt/lunar"
  version "0.0.1-beta05"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta05/lunar_Darwin_x86_64.tar.gz"
      sha256 "364e1899ab8100cdaab320eb362ed3a2f0895e0a81e7fac854c552462e160734"

      def install
        bin.install "lunar"
      end
    end
    on_arm do
      url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta05/lunar_Darwin_arm64.tar.gz"
      sha256 "7e1b452561cbbc1681afc35ff38702e6dcf585746becf5ececcf82c3b740b998"

      def install
        bin.install "lunar"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta05/lunar_Linux_x86_64.tar.gz"
        sha256 "72757466ab6f770332544108b5ab2872f0db3689e6596b2cfd1b164e178fa274"

        def install
          bin.install "lunar"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/leonvogt/lunar/releases/download/v0.0.1-beta05/lunar_Linux_arm64.tar.gz"
        sha256 "ae5783ab0fc2b2300e8f7a2885b3f61e4324ed643cffecf57918f239e555d149"

        def install
          bin.install "lunar"
        end
      end
    end
  end
end
