# This file was generated by GoReleaser. DO NOT EDIT.
cask "lunar-db" do
  name "lunar-db"
  desc "Database snapshot tool for PostgreSQL databases. Installs the `lunar` command."
  homepage "https://github.com/leonvogt/lunar"
  version "0.0.1-beta09"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lunar"

  on_macos do
    on_intel do
      url "https://github.com/leonvogt/lunar/releases/download/v#{version}/lunar_Darwin_x86_64.tar.gz"
      sha256 "a87d9fe6a8958adf478e41d64eda2c3f89d2b62e31f2521ed94838ffd17ea925"
    end
    on_arm do
      url "https://github.com/leonvogt/lunar/releases/download/v#{version}/lunar_Darwin_arm64.tar.gz"
      sha256 "fd9ff9053fd1f0041bd57badfb1fe6040534bdc0f6e83bec932d0e038e9c845d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/leonvogt/lunar/releases/download/v#{version}/lunar_Linux_x86_64.tar.gz"
      sha256 "c12fcca8c9cbbe9018b8ca777796219ad6e73df0e08dfa9bbb914d5efb909daa"
    end
    on_arm do
      url "https://github.com/leonvogt/lunar/releases/download/v#{version}/lunar_Linux_arm64.tar.gz"
      sha256 "30e7d1e60f482454b7e60103cf246ed6191e7e5bff8a4ad7eb479899fe46ad11"
    end
  end

  # No zap stanza required
end
